#include "BG770A-GL.h"
#include <main.h>

void bg770a_gl_init()
{
	// PWR ON
	HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_SET);

	// RESET
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_15, GPIO_PIN_SET); //CATM1_DOWN : LOW
	HAL_Delay(100);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_15, GPIO_PIN_RESET); //CATM1_DOWN : HIGH

	// PWR ON : Power-up Timing (When VBAT is Stable for More than 250 ms)
	HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_SET); //CATM1_VBAT_ON : HIGH
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_SET); //CATM1_POWER : HIGH
	HAL_Delay(300);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_13, GPIO_PIN_SET); //CATM1_DOWN : HIGH
	HAL_Delay(50);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_RESET); //CATM1_POWER : LOW
	HAL_Delay(700);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_RESET); //CATM1_POWER : HIGH
}
